// ─── Demo Mode ────────────────────────────────────────────────────────────────
// Set VITE_DEMO_MODE=true in your Vercel environment variables to force demo
// data without any API connection. Even in live mode, all pages fall back to
// this data if the API is unreachable.

export const DEMO_MODE = import.meta.env.VITE_DEMO_MODE === "true";

// ─── Summary Data (used by Dashboard) ─────────────────────────────────────────
// Reflects actual benchmark results recorded on 2026-06-12 (temp 0.0).

export const demoSummary = {
  "qwen2.5:3b": {
    average_ttft: 0.8105,
    average_latency: 3.9828,
    average_tokens_per_second: 40.17,
    prompts_tested: 5,
  },
  "llama3.2:3b": {
    average_ttft: 9.7877,
    average_latency: 11.4917,
    average_tokens_per_second: 19.14,
    prompts_tested: 5,
  },
  "phi3:mini": {
    average_ttft: 8.2143,
    average_latency: 12.011,
    average_tokens_per_second: 32.82,
    prompts_tested: 5,
  },
};

// ─── Individual Run Logs (used by BenchmarkRuns & Comparison) ─────────────────
// 15 rows: 3 models × 5 prompts @ temp 0.0, 15 rows @ temp 0.7

export const demoRuns = [
  // ── qwen2.5:3b @ temp 0.0 ──────────────────────────────────────────────────
  {
    id: 1,
    model_name: "qwen2.5:3b",
    prompt_name: "reasoning_1",
    prompt_category: "reasoning",
    prompt_difficulty: "easy",
    ttft_seconds: 0.72,
    latency_seconds: 3.41,
    tokens_per_second: 42.1,
    temperature: 0.0,
    created_at: "2026-06-12T06:55:00Z",
  },
  {
    id: 2,
    model_name: "qwen2.5:3b",
    prompt_name: "reasoning_2",
    prompt_category: "reasoning",
    prompt_difficulty: "medium",
    ttft_seconds: 0.81,
    latency_seconds: 4.12,
    tokens_per_second: 39.8,
    temperature: 0.0,
    created_at: "2026-06-12T06:55:20Z",
  },
  {
    id: 3,
    model_name: "qwen2.5:3b",
    prompt_name: "coding_1",
    prompt_category: "coding",
    prompt_difficulty: "medium",
    ttft_seconds: 0.95,
    latency_seconds: 4.78,
    tokens_per_second: 38.5,
    temperature: 0.0,
    created_at: "2026-06-12T06:55:40Z",
  },
  {
    id: 4,
    model_name: "qwen2.5:3b",
    prompt_name: "summarization_1",
    prompt_category: "summarization",
    prompt_difficulty: "easy",
    ttft_seconds: 0.79,
    latency_seconds: 3.89,
    tokens_per_second: 41.2,
    temperature: 0.0,
    created_at: "2026-06-12T06:56:00Z",
  },
  {
    id: 5,
    model_name: "qwen2.5:3b",
    prompt_name: "extraction_1",
    prompt_category: "extraction",
    prompt_difficulty: "easy",
    ttft_seconds: 0.69,
    latency_seconds: 3.68,
    tokens_per_second: 39.2,
    temperature: 0.0,
    created_at: "2026-06-12T06:56:20Z",
  },
  // ── llama3.2:3b @ temp 0.0 ─────────────────────────────────────────────────
  {
    id: 6,
    model_name: "llama3.2:3b",
    prompt_name: "reasoning_1",
    prompt_category: "reasoning",
    prompt_difficulty: "easy",
    ttft_seconds: 9.21,
    latency_seconds: 10.88,
    tokens_per_second: 21.4,
    temperature: 0.0,
    created_at: "2026-06-12T06:58:00Z",
  },
  {
    id: 7,
    model_name: "llama3.2:3b",
    prompt_name: "reasoning_2",
    prompt_category: "reasoning",
    prompt_difficulty: "medium",
    ttft_seconds: 10.11,
    latency_seconds: 12.1,
    tokens_per_second: 18.2,
    temperature: 0.0,
    created_at: "2026-06-12T06:59:00Z",
  },
  {
    id: 8,
    model_name: "llama3.2:3b",
    prompt_name: "coding_1",
    prompt_category: "coding",
    prompt_difficulty: "medium",
    ttft_seconds: 10.44,
    latency_seconds: 12.78,
    tokens_per_second: 17.9,
    temperature: 0.0,
    created_at: "2026-06-12T07:00:00Z",
  },
  {
    id: 9,
    model_name: "llama3.2:3b",
    prompt_name: "summarization_1",
    prompt_category: "summarization",
    prompt_difficulty: "easy",
    ttft_seconds: 9.88,
    latency_seconds: 11.22,
    tokens_per_second: 20.1,
    temperature: 0.0,
    created_at: "2026-06-12T07:01:00Z",
  },
  {
    id: 10,
    model_name: "llama3.2:3b",
    prompt_name: "extraction_1",
    prompt_category: "extraction",
    prompt_difficulty: "easy",
    ttft_seconds: 9.22,
    latency_seconds: 10.44,
    tokens_per_second: 17.97,
    temperature: 0.0,
    created_at: "2026-06-12T07:02:00Z",
  },
  // ── phi3:mini @ temp 0.0 ───────────────────────────────────────────────────
  {
    id: 11,
    model_name: "phi3:mini",
    prompt_name: "reasoning_1",
    prompt_category: "reasoning",
    prompt_difficulty: "easy",
    ttft_seconds: 7.88,
    latency_seconds: 11.34,
    tokens_per_second: 34.1,
    temperature: 0.0,
    created_at: "2026-06-12T07:04:00Z",
  },
  {
    id: 12,
    model_name: "phi3:mini",
    prompt_name: "reasoning_2",
    prompt_category: "reasoning",
    prompt_difficulty: "medium",
    ttft_seconds: 8.44,
    latency_seconds: 12.88,
    tokens_per_second: 31.9,
    temperature: 0.0,
    created_at: "2026-06-12T07:05:00Z",
  },
  {
    id: 13,
    model_name: "phi3:mini",
    prompt_name: "coding_1",
    prompt_category: "coding",
    prompt_difficulty: "medium",
    ttft_seconds: 8.91,
    latency_seconds: 13.44,
    tokens_per_second: 30.2,
    temperature: 0.0,
    created_at: "2026-06-12T07:06:00Z",
  },
  {
    id: 14,
    model_name: "phi3:mini",
    prompt_name: "summarization_1",
    prompt_category: "summarization",
    prompt_difficulty: "easy",
    ttft_seconds: 7.99,
    latency_seconds: 11.78,
    tokens_per_second: 33.5,
    temperature: 0.0,
    created_at: "2026-06-12T07:07:00Z",
  },
  {
    id: 15,
    model_name: "phi3:mini",
    prompt_name: "extraction_1",
    prompt_category: "extraction",
    prompt_difficulty: "easy",
    ttft_seconds: 7.87,
    latency_seconds: 10.61,
    tokens_per_second: 34.39,
    temperature: 0.0,
    created_at: "2026-06-12T07:08:00Z",
  },
  // ── qwen2.5:3b @ temp 0.7 ──────────────────────────────────────────────────
  {
    id: 16,
    model_name: "qwen2.5:3b",
    prompt_name: "reasoning_1",
    prompt_category: "reasoning",
    prompt_difficulty: "easy",
    ttft_seconds: 2.88,
    latency_seconds: 5.77,
    tokens_per_second: 37.4,
    temperature: 0.7,
    created_at: "2026-06-12T07:10:00Z",
  },
  {
    id: 17,
    model_name: "qwen2.5:3b",
    prompt_name: "reasoning_2",
    prompt_category: "reasoning",
    prompt_difficulty: "medium",
    ttft_seconds: 3.12,
    latency_seconds: 6.22,
    tokens_per_second: 35.8,
    temperature: 0.7,
    created_at: "2026-06-12T07:10:30Z",
  },
  {
    id: 18,
    model_name: "qwen2.5:3b",
    prompt_name: "coding_1",
    prompt_category: "coding",
    prompt_difficulty: "medium",
    ttft_seconds: 3.44,
    latency_seconds: 6.91,
    tokens_per_second: 34.2,
    temperature: 0.7,
    created_at: "2026-06-12T07:11:00Z",
  },
  {
    id: 19,
    model_name: "qwen2.5:3b",
    prompt_name: "summarization_1",
    prompt_category: "summarization",
    prompt_difficulty: "easy",
    ttft_seconds: 2.91,
    latency_seconds: 5.88,
    tokens_per_second: 36.9,
    temperature: 0.7,
    created_at: "2026-06-12T07:11:30Z",
  },
  {
    id: 20,
    model_name: "qwen2.5:3b",
    prompt_name: "extraction_1",
    prompt_category: "extraction",
    prompt_difficulty: "easy",
    ttft_seconds: 2.72,
    latency_seconds: 5.55,
    tokens_per_second: 36.18,
    temperature: 0.7,
    created_at: "2026-06-12T07:12:00Z",
  },
  // ── llama3.2:3b @ temp 0.7 ─────────────────────────────────────────────────
  {
    id: 21,
    model_name: "llama3.2:3b",
    prompt_name: "reasoning_1",
    prompt_category: "reasoning",
    prompt_difficulty: "easy",
    ttft_seconds: 1.71,
    latency_seconds: 3.22,
    tokens_per_second: 35.6,
    temperature: 0.7,
    created_at: "2026-06-12T07:13:00Z",
  },
  {
    id: 22,
    model_name: "llama3.2:3b",
    prompt_name: "reasoning_2",
    prompt_category: "reasoning",
    prompt_difficulty: "medium",
    ttft_seconds: 1.88,
    latency_seconds: 3.55,
    tokens_per_second: 33.9,
    temperature: 0.7,
    created_at: "2026-06-12T07:13:30Z",
  },
  {
    id: 23,
    model_name: "llama3.2:3b",
    prompt_name: "coding_1",
    prompt_category: "coding",
    prompt_difficulty: "medium",
    ttft_seconds: 1.94,
    latency_seconds: 3.71,
    tokens_per_second: 32.8,
    temperature: 0.7,
    created_at: "2026-06-12T07:14:00Z",
  },
  {
    id: 24,
    model_name: "llama3.2:3b",
    prompt_name: "summarization_1",
    prompt_category: "summarization",
    prompt_difficulty: "easy",
    ttft_seconds: 1.78,
    latency_seconds: 3.38,
    tokens_per_second: 35.0,
    temperature: 0.7,
    created_at: "2026-06-12T07:14:30Z",
  },
  {
    id: 25,
    model_name: "llama3.2:3b",
    prompt_name: "extraction_1",
    prompt_category: "extraction",
    prompt_difficulty: "easy",
    ttft_seconds: 1.69,
    latency_seconds: 3.18,
    tokens_per_second: 34.58,
    temperature: 0.7,
    created_at: "2026-06-12T07:15:00Z",
  },
  // ── phi3:mini @ temp 0.7 ───────────────────────────────────────────────────
  {
    id: 26,
    model_name: "phi3:mini",
    prompt_name: "reasoning_1",
    prompt_category: "reasoning",
    prompt_difficulty: "easy",
    ttft_seconds: 0.71,
    latency_seconds: 3.11,
    tokens_per_second: 37.8,
    temperature: 0.7,
    created_at: "2026-06-12T07:16:00Z",
  },
  {
    id: 27,
    model_name: "phi3:mini",
    prompt_name: "reasoning_2",
    prompt_category: "reasoning",
    prompt_difficulty: "medium",
    ttft_seconds: 0.88,
    latency_seconds: 3.44,
    tokens_per_second: 36.1,
    temperature: 0.7,
    created_at: "2026-06-12T07:16:30Z",
  },
  {
    id: 28,
    model_name: "phi3:mini",
    prompt_name: "coding_1",
    prompt_category: "coding",
    prompt_difficulty: "medium",
    ttft_seconds: 0.94,
    latency_seconds: 3.61,
    tokens_per_second: 35.2,
    temperature: 0.7,
    created_at: "2026-06-12T07:17:00Z",
  },
  {
    id: 29,
    model_name: "phi3:mini",
    prompt_name: "summarization_1",
    prompt_category: "summarization",
    prompt_difficulty: "easy",
    ttft_seconds: 0.72,
    latency_seconds: 3.18,
    tokens_per_second: 37.2,
    temperature: 0.7,
    created_at: "2026-06-12T07:17:30Z",
  },
  {
    id: 30,
    model_name: "phi3:mini",
    prompt_name: "extraction_1",
    prompt_category: "extraction",
    prompt_difficulty: "easy",
    ttft_seconds: 0.67,
    latency_seconds: 2.98,
    tokens_per_second: 37.65,
    temperature: 0.7,
    created_at: "2026-06-12T07:18:00Z",
  },
];
